# Generated by Django 2.0.2 on 2019-05-28 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0035_auto_20190526_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, max_length=200)),
                ('committee1', models.CharField(blank=True, max_length=200)),
                ('committee2', models.CharField(blank=True, max_length=200)),
                ('committee3', models.CharField(blank=True, max_length=200)),
                ('committee4', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 28, 16, 30, 58, 369015)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 16, 30, 58, 371007)),
        ),
    ]
