# Generated by Django 2.1.2 on 2019-05-29 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0053_auto_20190529_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 16, 48, 34, 427641)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 16, 48, 34, 428639)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bsc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bsc_grad_institute',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bsc_year',
            field=models.IntegerField(blank=True, choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='msc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='msc_grad_institute',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='msc_year',
            field=models.IntegerField(blank=True, choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd_grad_institute',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd_year',
            field=models.IntegerField(blank=True, choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
