# Generated by Django 2.1.2 on 2019-05-29 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0056_auto_20190529_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 17, 23, 35, 791661)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 23, 35, 792637)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bsc_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='msc_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd_year',
            field=models.IntegerField(choices=[(2550, 2550), (2551, 2551), (2552, 2552), (2553, 2553), (2554, 2554), (2555, 2555), (2556, 2556), (2557, 2557), (2558, 2558), (2559, 2559), (2560, 2560), (2561, 2561), (2562, 2562)], default=2019, verbose_name='year'),
        ),
    ]
