# Generated by Django 2.1.2 on 2019-05-29 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0057_auto_20190529_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 17, 25, 16, 119758)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 25, 16, 120755)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
