# Generated by Django 2.1.2 on 2019-05-29 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0058_auto_20190529_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 17, 26, 1, 646178)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 17, 26, 1, 647176)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
