# Generated by Django 2.0 on 2019-06-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0086_auto_20190601_1153'),
        ('study_program', '0054_auto_20190529_1809'),
    ]

    operations = [
    ]
