# Generated by Django 2.0 on 2019-06-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0090_auto_20190610_1206'),
        ('study_program', '0087_merge_20190606_1614'),
    ]

    operations = [
    ]
