# Generated by Django 2.0 on 2019-06-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0091_merge_20190610_1245'),
        ('study_program', '0087_auto_20190606_1249'),
    ]

    operations = [
    ]
