# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class TestCase9CreateCommitteeAppointment(unittest.TestCase):
    def setUp(self):
        print()
        print("test case 9-1: create committee appointment ")
        chromedriver = "./chromedriver"
        self.driver = webdriver.Chrome(chromedriver)
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.katalon.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_case9_create_committee_appointment(self):
        driver = self.driver
        driver.get("http://127.0.0.1:8000/")
        driver.find_element_by_name("username").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("eng")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("eng")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-07")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_available_in_morning").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"ENGAGIRCULBMT: หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเกษตร")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='eng'])[1]/following::nf[1]").click()
        driver.find_element_by_id("login-right").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("itx")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("itx")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-07")
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"ITXINFORMABMT: หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสารสนเทศ")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_id("sign-out-alt").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("ami")
        driver.find_element_by_name("password").click()
        driver.find_element_by_name("password").click()
        driver.find_element_by_name("password").click()
        # ERROR: Caught exception [ERROR: Unsupported command [doubleClick | name=password | ]]
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("ami")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_id("Faculty-btn").click()
        driver.find_element_by_id("Appointment-btn").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-08")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"AMIMANUFACBMT: วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมระบบการผลิต")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_id("sign-out-alt").click()
        driver.find_element_by_id("login-right").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("icx")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("icx")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-09")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [removeSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"ICXENGNTECBNI: หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการจัดการวิศวกรรมและเทคโนโลยี (หลักสูตรนานาชาติ)")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_link_text("Logout").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("nnt")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("nnt")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-10")
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"NNTNANOMATBMT: วิศวกรรมศาสตรบัณฑิต สาขาวิศวกรรมวัสดุนาโน")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='nnt'])[1]/following::nf[1]").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("mse")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("mse")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_id("Faculty-btn").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-10")
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : จันทนี เพชรานนท์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[3]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"MSEMUSICENBMT: หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมดนตรีและสื่อประสม")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_id("sign-out-alt").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='IQA System'])[1]/following::div[2]").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("aai")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("aai")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-11")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : จันทนี เพชรานนท์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[3]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : นคร ศรีสุขุมบวรชัย]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[4]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"AAILOGIMANBNI: หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการจัดการโลจิสติกส์ (หลักสูตรนานาชาติ)")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='aai'])[1]/following::nf[1]").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("adm")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("adm")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_id("Faculty-btn").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-11")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : นคร ศรีสุขุมบวรชัย]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[4]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : จันทนี เพชรานนท์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[3]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"ADMBUSADMIBNI: หลักสูตรบริหารธุรกิจบัณฑิต (หลักสูตรนานาชาติ)")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_id("sign-out-alt").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='IQA System'])[1]/following::div[2]").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("ide")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("ide")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-12")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : ชัยวัฒน์ หนูทอง]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[5]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"IDEAGRIEDUBMT: หลักสูตรครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาครุศาสตร์เกษตร")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='ide'])[1]/following::nf[1]").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("agt")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("agt")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("agt")
        driver.find_element_by_name("password").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("agt")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("agi")
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("agi")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Create Appointment Time'])[1]/following::form[1]").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-06-12")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : ชัยวัฒน์ หนูทอง]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[5]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"AGIFERMENTBMT: หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีการหมัก")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='agi'])[1]/following::nf[1]").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("lba")
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("lba")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)=concat('Faculty', \"'\", 'sStudy Program(หลักสูตรในคณะ)___________________')])[1]/following::b[2]").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-07-16")
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"LBATOURHOSBNT: หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชานวัตกรรมการท่องเที่ยวและการบริการ")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='lba'])[1]/following::nf[1]").click()
        driver.find_element_by_id("login-right").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("arc")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("arc")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_id("Appointment-btn").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-07-21")
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วิบูลย์ พร้อมพานิชย์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[2]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"ARC3DBASEDBMT: หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาการออกแบบสนเทศสามมิติ")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='arc'])[1]/following::nf[1]").click()
        driver.find_element_by_xpath("//div[@id='login-container']/div").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("sci")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("sci")
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::input[3]").click()
        driver.find_element_by_xpath(u"(.//*[normalize-space(text()) and normalize-space(.)='Assessment(การประเมินผล)___________________'])[1]/following::b[2]").click()
        driver.find_element_by_id("Appointment-btn").click()
        driver.find_element_by_id("committee_appointment-btn").click()
        driver.find_element_by_id("id_available_in_morning").click()
        Select(driver.find_element_by_id("id_available_in_morning")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_morning").click()
        driver.find_element_by_id("id_available_in_afternoon").click()
        Select(driver.find_element_by_id("id_available_in_afternoon")).select_by_visible_text("yes")
        driver.find_element_by_id("id_available_in_afternoon").click()
        driver.find_element_by_id("id_appointment_date").click()
        driver.find_element_by_id("id_appointment_date").clear()
        driver.find_element_by_id("id_appointment_date").send_keys("2562-07-29")
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : วสุ อุดมเพทายกุล]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[1]").click()
        # ERROR: Caught exception [ERROR: Unsupported command [addSelection | id=id_appointed_committee | label=2561 : จันทนี เพชรานนท์]]
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Appointed committee'])[1]/following::option[3]").click()
        driver.find_element_by_id("id_appointed_program").click()
        Select(driver.find_element_by_id("id_appointed_program")).select_by_visible_text(u"SCIPETROCHBNI: หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาปิโตรเคมี (หลักสูตรนานาชาติ)")
        driver.find_element_by_id("id_appointed_program").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::input[2]").click()
        driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='sci'])[1]/following::nf[1]").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
